<?php
/**
 * Returns Page Header Banner
 * @param String $title      Page Title (optional).
 * @param String $image      Background image for the header banner (optional).
 */

function page_header_banner( $title = '', $image = '' ){
    
    $phb_title = '';
    $phb_banner = ''; 
        
    if ( is_plugin_active( 'advanced-custom-fields-pro/acf.php' ) ):
        $page_id = is_home() || is_category() || is_author() ? get_option( 'page_for_posts' ) : '';
        $acf_title = get_field( "page_title", $page_id ); // Get from the specific page (Generated by Advanced Custom Fields Plugin)
        $acf_banner = get_field( "page_banner", $page_id ); // Get from the specific page (Generated by Advanced Custom Fields Plugin)

        $bts_general_banner = BTS::$options['page_settings']['header_banner']; // Get from the theme options.
    endif;
    
    $post_featured_image = get_the_post_thumbnail_url( null, 'full' ); // Get the featured image of the post
    
    if( $title !== '' ){
        $phb_title = $title;
    }elseif( $acf_title ){
        $phb_title = $acf_title;
    }else{
        $phb_title = get_the_title();
    }

    if( $image !== '' ){
        $phb_banner = $image;
    }elseif( $acf_banner ){ 
        $phb_banner = $acf_banner['url']; 
    }elseif( $post_featured_image ){
        $phb_banner = $post_featured_image;
    }elseif( !empty( $bts_general_banner ) ){
        $phb_banner = $bts_general_banner['url'];     
    }else{
        $phb_banner = bagels_get_default_image( 'header-banner' ); 
    }
    
    $html = '
            <div class="page-header-banner">
                <div class="phb-bg" style="background-image: url( '. esc_url( $phb_banner ) .' );"></div>
                <div class="container">
                    <div class="phb-content">
                        <h1 class="phb-heading">'.__( $phb_title, 'bagels' ).'</h1>
                    </div>
                </div> 
            </div>
    ';
    return $html;
}